### ISSUE TITLE
App crashes in certain situations 

### ISSUE THREAD

**Issue by xd003** [Ryuk-me/Torrents-Api#8]
I have noticed that the app would randomly crash sometimes . I don't know a very definite way to reproduce it but my best guess is that it happens in torlock only. Thankfully i managed to capture the whole log which should help you to fix this

```
2021-06-18T13:23:30.860043+00:00 heroku[router]: at=info method=GET path="/torlock/test" host=api-aggreator.herokuapp.com request_id=beb97f34-fd1a-47cf-ac7f-3ded23707ad0 fwd="103.58.152.254" dyno=web.1 connect=1ms service=8ms status=200 bytes=307 protocol=https
2021-06-18T13:23:37.231963+00:00 heroku[router]: at=info method=GET path="/api/torlock/test" host=api-aggreator.herokuapp.com request_id=d1e7ccfc-042c-4a0e-8fbd-a846ee120c82 fwd="103.58.152.254" dyno=web.1 connect=0ms service=41ms status=200 bytes=357 protocol=https
2021-06-18T13:23:44.603326+00:00 heroku[router]: at=info method=GET path="/api/torlock/test" host=api-aggreator.herokuapp.com request_id=7d4a118a-581a-438d-bdda-9fc7fe8847e9 fwd="103.58.152.254" dyno=web.1 connect=0ms service=38ms status=304 bytes=260 protocol=https
2021-06-18T13:23:47.228749+00:00 heroku[router]: at=info method=GET path="/api/torlock/test" host=api-aggreator.herokuapp.com request_id=614d1a16-0458-4075-8811-7f34761ee165 fwd="103.58.152.254" dyno=web.1 connect=0ms service=30ms status=304 bytes=260 protocol=https
2021-06-18T13:23:56.179890+00:00 heroku[router]: at=info method=GET path="/api/torlock/test" host=api-aggreator.herokuapp.com request_id=34e37bf1-91e2-4038-82f1-7f89e7982137 fwd="103.58.152.254" dyno=web.1 connect=0ms service=23ms status=304 bytes=260 protocol=https
2021-06-18T13:24:00.706574+00:00 heroku[router]: at=info method=GET path="/api/torlock/test" host=api-aggreator.herokuapp.com request_id=b958ed5f-1e32-47bd-8114-272e27e26704 fwd="103.58.152.254" dyno=web.1 connect=0ms service=33ms status=304 bytes=260 protocol=https
2021-06-18T13:24:03.421235+00:00 heroku[router]: at=info method=GET path="/api/torlock/test" host=api-aggreator.herokuapp.com request_id=01abc069-9a67-4930-8d88-6b65f8cb260c fwd="103.58.152.254" dyno=web.1 connect=0ms service=29ms status=304 bytes=260 protocol=https
2021-06-18T13:24:06.152022+00:00 heroku[router]: at=info method=GET path="/api/torlock/test" host=api-aggreator.herokuapp.com request_id=88e86233-c0ec-4aba-8b1b-99ece4af3a83 fwd="103.58.152.254" dyno=web.1 connect=0ms service=35ms status=304 bytes=260 protocol=https
2021-06-18T13:24:08.651676+00:00 heroku[router]: at=info method=GET path="/api/torlock/test" host=api-aggreator.herokuapp.com request_id=6dc2c212-a3f6-40bd-9c61-c8d2dbb1b806 fwd="103.58.152.254" dyno=web.1 connect=0ms service=35ms status=304 bytes=260 protocol=https
2021-06-18T13:24:12.369523+00:00 heroku[router]: at=info method=GET path="/api/torlock/test" host=api-aggreator.herokuapp.com request_id=6eb6f282-0115-47f7-9d05-35ce21a178c2 fwd="103.58.152.254" dyno=web.1 connect=3ms service=35ms status=304 bytes=260 protocol=https
2021-06-18T13:24:24.084659+00:00 heroku[router]: at=info method=GET path="/api/torlock/test" host=api-aggreator.herokuapp.com request_id=e6b92e60-acd0-48b9-bdf2-f031011e5eea fwd="103.58.152.254" dyno=web.1 connect=10ms service=69ms status=304 bytes=260 protocol=https
2021-06-18T13:24:26.613818+00:00 heroku[router]: at=info method=GET path="/api/torlock/test" host=api-aggreator.herokuapp.com request_id=a07d5c91-e13e-48ff-9082-4f76f3fbd5e7 fwd="103.58.152.254" dyno=web.1 connect=3ms service=45ms status=304 bytes=260 protocol=https
2021-06-18T13:24:28.996377+00:00 heroku[router]: at=info method=GET path="/api/torlock/test" host=api-aggreator.herokuapp.com request_id=f947c462-1ee0-4a0e-a89c-0a9fac82ce61 fwd="103.58.152.254" dyno=web.1 connect=1ms service=73ms status=304 bytes=260 protocol=https
2021-06-18T13:24:31.201634+00:00 heroku[router]: at=info method=GET path="/api/torlock/test" host=api-aggreator.herokuapp.com request_id=cea56caa-5ef2-4ca4-ae26-9b54ab51fcb0 fwd="103.58.152.254" dyno=web.1 connect=2ms service=49ms status=304 bytes=260 protocol=https
2021-06-18T13:24:51.505453+00:00 app[web.1]: (node:4) UnhandledPromiseRejectionWarning: Error: Request failed with status code 404
2021-06-18T13:24:51.505503+00:00 app[web.1]:     at createError (/app/node_modules/axios/lib/core/createError.js:16:15)
2021-06-18T13:24:51.505503+00:00 app[web.1]:     at settle (/app/node_modules/axios/lib/core/settle.js:17:12)
2021-06-18T13:24:51.505504+00:00 app[web.1]:     at IncomingMessage.handleStreamEnd (/app/node_modules/axios/lib/adapters/http.js:260:11)
2021-06-18T13:24:51.505505+00:00 app[web.1]:     at IncomingMessage.emit (events.js:387:35)
2021-06-18T13:24:51.505506+00:00 app[web.1]:     at endReadableNT (internal/streams/readable.js:1317:12)
2021-06-18T13:24:51.505506+00:00 app[web.1]:     at processTicksAndRejections (internal/process/task_queues.js:82:21)
2021-06-18T13:24:51.505506+00:00 app[web.1]: (Use `node --trace-warnings ...` to show where the warning was created)
2021-06-18T13:24:51.515878+00:00 app[web.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 16)
2021-06-18T13:24:51.516022+00:00 app[web.1]: (node:4) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2021-06-18T13:25:18.174424+00:00 heroku[router]: at=info method=GET path="/api/torlock/test" host=api-aggreator.herokuapp.com request_id=987bfdb0-9dfb-4dc0-9a87-48481a6057b2 fwd="103.58.152.254" dyno=web.1 connect=7ms service=502ms status=304 bytes=260 protocol=https
2021-06-18T13:25:18.479267+00:00 heroku[router]: at=error code=H12 desc="Request timeout" method=GET path="/api/torlock/attack" host=api-aggreator.herokuapp.com request_id=d9bef0b2-0c86-45a7-96e7-627a6318bb06 fwd="34.254.204.118" dyno=web.1 connect=1ms service=30000ms status=503 bytes=0 protocol=https
2021-06-18T13:25:21.983628+00:00 heroku[router]: at=info method=GET path="/api/torlock/test" host=api-aggreator.herokuapp.com request_id=370be524-261e-4ed2-a792-3221ed0b51b0 fwd="103.58.152.254" dyno=web.1 connect=3ms service=71ms status=304 bytes=260 protocol=https
Disconnected from log stream. There may be events happening that you do not see here! Attempting to reconnect...
2021-06-18T13:24:51.505504+00:00 app[web.1]:     at IncomingMessage.handleStreamEnd (/app/node_modules/axios/lib/adapters/http.js:260:11)
2021-06-18T13:24:51.505505+00:00 app[web.1]:     at IncomingMessage.emit (events.js:387:35)
2021-06-18T13:24:51.505506+00:00 app[web.1]:     at endReadableNT (internal/streams/readable.js:1317:12)
2021-06-18T13:24:51.505506+00:00 app[web.1]:     at processTicksAndRejections (internal/process/task_queues.js:82:21)
2021-06-18T13:24:51.505506+00:00 app[web.1]: (Use `node --trace-warnings ...` to show where the warning was created)
2021-06-18T13:24:51.515878+00:00 app[web.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 16)
2021-06-18T13:24:51.516022+00:00 app[web.1]: (node:4) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2021-06-18T13:25:18.174424+00:00 heroku[router]: at=info method=GET path="/api/torlock/test" host=api-aggreator.herokuapp.com request_id=987bfdb0-9dfb-4dc0-9a87-48481a6057b2 fwd="103.58.152.254" dyno=web.1 connect=7ms service=502ms status=304 bytes=260 protocol=https
2021-06-18T13:25:18.479267+00:00 heroku[router]: at=error code=H12 desc="Request timeout" method=GET path="/api/torlock/attack" host=api-aggreator.herokuapp.com request_id=d9bef0b2-0c86-45a7-96e7-627a6318bb06 fwd="34.254.204.118" dyno=web.1 connect=1ms service=30000ms status=503 bytes=0 protocol=https
2021-06-18T13:25:21.983628+00:00 heroku[router]: at=info method=GET path="/api/torlock/test" host=api-aggreator.herokuapp.com request_id=370be524-261e-4ed2-a792-3221ed0b51b0 fwd="103.58.152.254" dyno=web.1 connect=3ms service=71ms status=304 bytes=260 protocol=https
2021-06-18T13:25:40.091586+00:00 heroku[router]: at=info method=GET path="/api/torlock/test" host=api-aggreator.herokuapp.com request_id=fb41cf96-ade6-4593-9b6c-eade979d7766 fwd="49.33.220.252" dyno=web.1 connect=0ms service=34ms status=304 bytes=260 protocol=https
2021-06-18T13:26:13.659158+00:00 heroku[router]: at=info method=GET path="/api/torlock/test" host=api-aggreator.herokuapp.com request_id=f3a53fc4-f838-4f72-b2ad-a3684d6f1c1f fwd="49.33.220.252" dyno=web.1 connect=0ms service=46ms status=304 bytes=260 protocol=https
2021-06-18T13:26:22.923812+00:00 app[web.1]: (node:4) UnhandledPromiseRejectionWarning: Error: Request failed with status code 404
2021-06-18T13:26:22.923824+00:00 app[web.1]:     at createError (/app/node_modules/axios/lib/core/createError.js:16:15)
2021-06-18T13:26:22.923824+00:00 app[web.1]:     at settle (/app/node_modules/axios/lib/core/settle.js:17:12)
2021-06-18T13:26:22.923824+00:00 app[web.1]:     at IncomingMessage.handleStreamEnd (/app/node_modules/axios/lib/adapters/http.js:260:11)
2021-06-18T13:26:22.923826+00:00 app[web.1]:     at IncomingMessage.emit (events.js:387:35)
2021-06-18T13:26:22.923827+00:00 app[web.1]:     at endReadableNT (internal/streams/readable.js:1317:12)
2021-06-18T13:26:22.923827+00:00 app[web.1]:     at processTicksAndRejections (internal/process/task_queues.js:82:21)
2021-06-18T13:26:22.923955+00:00 app[web.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 22)
2021-06-18T13:26:50.553176+00:00 heroku[router]: at=error code=H12 desc="Request timeout" method=GET path="/api/torlock/attack" host=api-aggreator.herokuapp.com request_id=232b03ab-4d71-4e07-a812-fa8546eb6e48 fwd="49.33.220.252" dyno=web.1 connect=0ms service=30001ms status=503 bytes=0 protocol=https
```

**Comment by Ryuk-me** [comment]
added exception handling to every request so that app not crash.
it will probably fix the issue.
